xwayland {
	force_zero_scaling = true
}
env = GDK_SCALE,2

### dolphin file association fix
env = XDG_MENU_PREFIX,plasma-

exec-once = kbuildsycoca6 –noincremental

exec-once = printf “[D-BUS Service]\nName=org.kde.kded6\nExec=/bin/false” > $HOME/.local/share/dbus-1/services/org.kde.kded6.service

exec-shutdown = rm $HOME/.local/share/dbus-1/services/org.kde.kded6.service
