input {
	kb_layout = no
	kb_variant =
	kb_model =
	kb_options =
	kb_rules =

	follow_mouse = 1

	sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

	touchpad {
		natural_scroll = false
	}
}

device {
	name = epic-mouse-v1
	sensitivity = -0.5
}
device {
	name = kensington-expert-mouse
	sensitivity = -0.75
	#left_handed = true
}
device {
	name = logitech-g-pro--1
	sensitivity = -0.3
}
device {
	name = logitech-gaming-mouse-g600
	sensitivity = -0.3
}

input { 
	kb_options = altwin:menu_win
}
